######################################################################
# Copyright (c) 2019-2022 Claudio André <claudioandre.br at gmail.com>
#
# This program comes with ABSOLUTELY NO WARRANTY; express or implied.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, as expressed in version 2, seen at
# http://www.gnu.org/licenses/gpl-2.0.html
######################################################################

FROM fedora:36
LABEL maintainer Claudio André (c) 2017-2022 1.0.Latest
LABEL software CI for John the Ripper

RUN dnf -y -q update && \
    dnf -y  --skip-broken  install \
        mingw32-gcc mingw64-gcc mingw32-gcc-c++ mingw64-gcc-c++ mingw32-libgomp mingw64-libgomp \
        mingw32-openssl mingw64-openssl mingw32-gmp mingw64-gmp mingw32-bzip2 mingw64-bzip2 \
        mingw32-wine-gecko mingw64-wine-gecko \
        @development-tools wine openssl-devel gmp-devel libpcap-devel bzip2-devel wget \
        clang libasan libubsan libtsan american-fuzzy-lop zzuf pocl-devel \
        american-fuzzy-lop-clang-fast && \
    useradd -U -m JtR

USER JtR
ENV BASE fedora
CMD /bin/bash
