######################################################################
# Copyright (c) 2019-2022 Claudio André <claudioandre.br at gmail.com>
#
# This program comes with ABSOLUTELY NO WARRANTY; express or implied.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, as expressed in version 2, seen at
# http://www.gnu.org/licenses/gpl-2.0.html
######################################################################

FROM fedora:37
LABEL maintainer Claudio André (c) 2017-2022 1.1.Flatpak
LABEL software Flatpak related CI for John the Ripper

RUN dnf -y -q update && \
    dnf -y    install \
        flatpak flatpak-builder elfutils wget git && \
    flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo && \
    flatpak install -y flathub org.freedesktop.Platform//22.08 org.freedesktop.Sdk//22.08 && \
    useradd -U -m JtR

USER JtR
ENV BASE fedora
CMD /bin/bash
